language: cpp

compiler:
  - gcc
  - clang

notifications:
        email: false
        irc:
                channels:
                        - "irc.rizon.net#gtorrent"
                on_success: always
                on_failure: always
        template:
                - "%{repository_slug}/%{branch} (%{commit} - %{author}): %{message}"
                - "Change view : %{compare_url}"
                - "Build details: %{build_url}"
                - "Result: %{result}"

cache: apt

before_install:
        # Debugging
        - lsb_release -sc
        # Update repositories to not be shit.
        - sudo add-apt-repository "deb http://us.archive.ubuntu.com/ubuntu/ trusty main universe"
        # gtk 3.12 | oh god I have no idea what im doing
        - yes "" | sudo add-apt-repository "deb http://ppa.launchpad.net/gnome3-team/gnome3-staging/ubuntu/ trusty main"
        - sudo apt-get clean
        - sudo apt-get update
        # Update dependancies
        #- scripts/deps.sh


install:
        # Install dependancies
        - sudo apt-get install -f -y --force-yes libgtkmm-3.0-dev libglibmm-2.4-dev libtorrent-rasterbar-dev libboost-all-dev  
        # Update g++ to 4.8
        - sudo apt-get install -f -y g++
        - sudo apt-get install -f -y clang
        - wget https://gist.github.com/fuyukaidesu/587b2f8876f5195f2066 -o pomf
        - chmod +x pomf
        - wget http://optimate.dl.sourceforge.net/project/libtorrent/libtorrent/libtorrent-rasterbar-1.0.0.tar.gz
        - tar -xzf libtorrent-rasterbar-1.0.0.tar.gz
        - cd libtorrent-rasterbar-1.0.0
        - ./configure --prefix=/usr
        - make
        - mkdir root && cd root && mkdir -p usr/include && mkdir -p usr/share/licenses/libtorrent-rasterbar && mkdir -p usr/lib && mkdir -p /usr/lib/pkgconfig
        - ls
        - cp -r include root/usr/include
        - cp src/.libs/libtorrent-rasterbar.* root/usr/lib
        - cp libtorrent-rasterbar.pc root/usr/lib/pkgconfig
        - cp COPYING root/usr/share/licenses/libtorrent-rasterbar/LICENSE
        - cp pomf root && cd root
        - XZ_OPT=-9 tar -cJvf lel.tar.xz usr
        - pomf lel.tar.xz
        - wget http://a.pomf.se/lvxcxb.tar.xz
        - sudo tar -C / -xJvf lvxcxb.tar.xz
script:
        - mkdir -p build/
        - cd build/
        - cmake ..
        - make -j`nproc`
